language: java
os: linux
env:
  global:
    - HAZELCAST_HOST=127.0.0.1:5701

sudo: required
jdk:
  - oraclejdk8

##services:
##  - rocketmq

script: mvn clean install cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
